return {}
-- local util = require('util.lspconfig')
--
-- return {
--   "pmizio/typescript-tools.nvim",
--   dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
--   opts = {
--     settings = {
--       -- spawn additional tsserver instance to calculate diagnostics on it
--       separate_diagnostic_server = true,
--       -- "change"|"insert_leave" determine when the client asks the server about diagnostic
--       publish_diagnostic_on = "insert_leave",
--       tsserver_plugins = {
--         -- for TypeScript v4.9+
--         "@styled/typescript-styled-plugin",
--         -- or for older TypeScript versions
--         -- "typescript-styled-plugin",
--       },
--     },
--     root_dir = util.root_pattern('.git', 'tsconfig.json', 'jsconfig.json', 'package.json'),
--   },
-- }
